# Generated by Django 6.0.3 on 2026-03-31 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('manual', 'Ship Manual'), ('sop', 'Standard Operating Procedure'), ('report', 'Technical Report'), ('noon_report', 'Noon Report'), ('drawing', 'Technical Drawing'), ('certificate', 'Certificate'), ('checklist', 'Checklist'), ('circular', 'Circular / Notice'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='ingestion.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='administration.vessel'),
        ),
    ]
