# Generated by Django 6.0.3 on 2026-03-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noonreport',
            name='ae_fo_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AE Fuel Oil consumption (MT)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='ae_lub_oil_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AE lube oil consumption (litres)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='ae_running_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total AE running hours for the day', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='air_temp',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Air temperature (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='barometric_pressure',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Barometric pressure (mbar)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='boiler_fo_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Boiler FO consumption (MT)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='cargo_condition',
            field=models.CharField(blank=True, choices=[('laden', 'Laden'), ('ballast', 'Ballast'), ('part_laden', 'Part Laden')], max_length=15),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='cargo_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cargo quantity (MT)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='draft_aft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aft draft (metres)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='draft_fore',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Forward draft (metres)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='draft_mean',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mean draft (metres)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='fw_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fresh water consumption (MT)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='fw_produced',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fresh water produced (MT)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='hours_steaming',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours steaming since last report', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='hours_stopped',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours stopped since last report', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='me_cylinder_oil_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ME cylinder oil consumption (litres)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='me_power_kw',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Main engine power output (kW)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='me_system_oil_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ME system oil consumption (litres)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='sea_water_temp',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Sea water temperature (°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='noonreport',
            name='visibility',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Visibility in nautical miles', max_digits=4, null=True),
        ),
    ]
