# Generated by Django 6.0.3 on 2026-04-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_noonreport_ae_fo_consumption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noonreport',
            old_name='do_consumption',
            new_name='bf_consumption',
        ),
        migrations.RenameField(
            model_name='noonreport',
            old_name='do_rob',
            new_name='bf_rob',
        ),
        migrations.AlterField(
            model_name='noonreport',
            name='bf_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bio Fuel consumption (MT)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='noonreport',
            name='bf_rob',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bio Fuel Remaining on Board (MT)', max_digits=8, null=True),
        ),
    ]
