# Generated by Django 6.0.3 on 2026-03-31 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_noonreport_ae_fo_consumption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoonReportImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/noon_report_imports/')),
                ('original_filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(help_text='csv or xlsx', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='pending', max_length=25)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=list, help_text='List of error messages per row')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noon_report_imports', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(help_text='Target vessel for this import', on_delete=django.db.models.deletion.CASCADE, related_name='noon_report_imports', to='administration.vessel')),
            ],
            options={
                'verbose_name': 'Noon Report Import',
                'verbose_name_plural': 'Noon Report Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=10)),
                ('raw_data', models.JSONField(default=dict, help_text='Original row data from the file')),
                ('errors', models.JSONField(blank=True, default=list, help_text='Validation errors for this row')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('noon_report', models.ForeignKey(blank=True, help_text='The NoonReport created from this row (if successful)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='administration.noonreport')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='analytics.noonreportimport')),
            ],
            options={
                'verbose_name': 'Import Row',
                'verbose_name_plural': 'Import Rows',
                'ordering': ['row_number'],
                'unique_together': {('import_job', 'row_number')},
            },
        ),
    ]
