# Generated by Django 6.0.3 on 2026-03-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='citation_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
