# Generated by Django 6.0.3 on 2026-03-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='graph',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
