# Generated by Django 6.0.3 on 2026-03-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatmessage_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='diagnosis',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('', 'No Feedback'), ('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partial', 'Partially Correct')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
