# Generated by Django 6.0.3 on 2026-03-31 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_noonreport_ae_fo_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('performance', 'Performance Anomaly'), ('system', 'System Failure'), ('ingestion', 'Ingestion Issue'), ('fuel', 'Abnormal Fuel Usage'), ('query', 'Query Failure')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='administration.vessel')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='dashboard_a_severit_a690d7_idx'), models.Index(fields=['is_read', '-created_at'], name='dashboard_a_is_read_a0fbaa_idx')],
            },
        ),
    ]
